apiVersion: apps/v1
kind: Deployment
metadata:
  name: wil-app-deployment
  labels:
    app: wil-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wil-app
  template:
    metadata:
      labels:
        app: wil-app
    spec:
      containers:
      - name: wil-app
        image: nginx:1.14.2
        ports:
        - containerPort: 8080
